# Generated by Django 4.1.2 on 2023-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.TextField(verbose_name="Títulos"),
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=320, primary_key=True, serialize=False),
                ),
                ("name", models.TextField(null=True, verbose_name="Nombre")),
                ("age", models.IntegerField(null=True, verbose_name="Edad")),
                (
                    "age_relevance",
                    models.IntegerField(
                        null=True, verbose_name="Relevancia de la edad"
                    ),
                ),
                ("genres_relevance", models.IntegerField(null=True)),
                ("auhtor_name", models.TextField(null=True)),
                (
                    "author_relevance",
                    models.IntegerField(null=True, verbose_name="Relevancia del autor"),
                ),
                (
                    "similar_authors_relevance",
                    models.IntegerField(
                        null=True, verbose_name="Relevancia de los autores similares"
                    ),
                ),
                (
                    "settings_relevance",
                    models.IntegerField(
                        null=True, verbose_name="Relevancia de la ambientación"
                    ),
                ),
                (
                    "pages_number",
                    models.IntegerField(null=True, verbose_name="Número de páginas"),
                ),
                (
                    "pages_number_relevance",
                    models.IntegerField(
                        null=True, verbose_name="Relevancia del número de páginas"
                    ),
                ),
                ("rating", models.IntegerField(null=True, verbose_name="Nota media")),
                (
                    "rating_relevance",
                    models.IntegerField(
                        null=True, verbose_name="Relevancia de la nota media"
                    ),
                ),
                (
                    "date_before",
                    models.DateField(null=True, verbose_name="Fecha anterior"),
                ),
                (
                    "date_after",
                    models.DateField(null=True, verbose_name="Fecha posterior"),
                ),
                (
                    "date_relevance",
                    models.IntegerField(
                        null=True, verbose_name="Relevancia de la fecha"
                    ),
                ),
                ("genres", models.ManyToManyField(null=True, to="main.genre")),
                ("settings", models.ManyToManyField(null=True, to="main.setting")),
                (
                    "similar_authors",
                    models.ManyToManyField(null=True, to="main.author"),
                ),
            ],
        ),
    ]
