# Generated by Django 4.1.2 on 2022-12-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("genre_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(verbose_name="Género")),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("setting_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(verbose_name="Ambientación")),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("isbn", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField(verbose_name="Título")),
                ("series", models.TextField(verbose_name="Saga")),
                ("author", models.TextField(verbose_name="Autor")),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Nota media"
                    ),
                ),
                ("description", models.TextField(verbose_name="Sinopsis")),
                ("language", models.TextField(verbose_name="Idioma")),
                ("pages_number", models.IntegerField(verbose_name="Número de páginas")),
                ("publish_date", models.DateField(verbose_name="Fecha de publicación")),
                ("cover", models.URLField(verbose_name="Portada")),
                ("genres", models.ManyToManyField(to="main.genre")),
                ("setting", models.ManyToManyField(to="main.setting")),
            ],
        ),
    ]
