# Generated by Django 4.1.2 on 2023-02-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.TextField(verbose_name="Títulos"),
        ),
    ]
