# Generated by Django 4.1.2 on 2022-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publish_date",
            field=models.DateField(null=True, verbose_name="Fecha de publicación"),
        ),
    ]
