# Generated by Django 4.1.2 on 2023-03-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_book_title_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="is_waiting",
            field=models.BooleanField(default=False),
        ),
    ]
