# Generated by Django 4.1.2 on 2022-12-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="num_ratings",
            field=models.IntegerField(default=1, verbose_name="Número de puntuaciones"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2, max_digits=3, verbose_name="Puntuación media"
            ),
        ),
    ]
