# Generated by Django 4.1.2 on 2023-03-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_usersession_is_waiting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="auhtor_name",
            new_name="author_name",
        ),
    ]
