# Generated by Django 4.1.4 on 2023-03-14 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_auhtor_name_usersession_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
