# Generated by Django 4.1.2 on 2022-12-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_book_num_ratings_alter_book_average_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(verbose_name="Autor")),
            ],
        ),
    ]
