# Generated by Django 4.1.4 on 2023-03-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_usersession_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="date_created",
            new_name="date_last_used",
        ),
    ]
