# Generated by Django 4.1.2 on 2022-12-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_book_author_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="isbn",
            new_name="book_id",
        ),
    ]
