# Generated by Django 4.1.2 on 2023-01-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_book_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages_number",
            field=models.IntegerField(null=True, verbose_name="Número de páginas"),
        ),
    ]
