# Generated by Django 4.1.2 on 2023-01-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_book_pages_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="authors",
        ),
    ]
